### ISSUE TITLE
Add links to "How can you be a part of it?"

### ISSUE THREAD

**Issue by optikfluffel** [StephanieBr/hackbeach#2]
It would be cool if the sections of "How can you be a part of it?" would be linked in a useful way.
My proposal would be:
- [x] "help to organise" -> http://wiki.hackbeach.in/doku.php?id=start#meetings
- [x] "provide a talk" -> http://frab.hackbeach.in/conference/hb0/proposal/new
- [x] "lead a workshop" -> http://frab.hackbeach.in/conference/hb0/proposal/new
- [x] "spread the word!" -> a share widget (twitter, facebook, mail?)

~~"attend as a participant" -> ???~~

**Comment by StephanieBr** [comment]
I've removed the "attend as a participant" section.
